### ISSUE TITLE
Rename money() function?

### ISSUE THREAD

**Issue by ziming** [calebporzio/awesome-helpers#11]
Some of the other popular money packages has a money helper function as well. Might want to rename the money() function here.

Examples:
https://github.com/akaunting/money
https://github.com/cknow/laravel-money

**Comment by peter279k** [comment]
Can you explain why it should change the function name? Name collision or another reason?

**Comment by ziming** [comment]
I would think there would be a name collision because their helper functions are named money() too

**Comment by peter279k** [comment]
To avoid the name collision, we can consider following PHP code:

```php
use function It\is\Namespace\money as the_money;
```

We can use the alias style to separate the same function name at same time.

**Comment by ziming** [comment]
`caleb_money()` would look nicer in a blade file

**Comment by calebporzio** [comment]
Interesting, I wonder how big of a problem this is - like how many people are using both packages (there's not a TON of GH stars on their repos).

I'm just going to close this out for now because it appears those packages offer non-helper function usages, and users can just use those. If anyone wants to re-open this in the future and propose a new solution, I'm cool with that.
